/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.99
 * Generated at: 2024-02-21 17:17:08 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("  <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN\" crossorigin=\"anonymous\">\n");
      out.write("  <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL\" crossorigin=\"anonymous\"></script>\n");
      out.write("  <style>\n");
      out.write("    body {\n");
      out.write("      background-color: #ffcc00;\n");
      out.write("      color: #fff;\n");
      out.write("      background-image: url('https://static.vecteezy.com/system/resources/thumbnails/002/018/246/original/abstract-colorful-pastel-gradient-background-free-video.jpg');\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .card {\n");
      out.write("      border-radius: 1rem;\n");
      out.write("      /*background-color: #fff;*/\n");
      out.write("      border: none;\n");
      out.write("      /* Card background color */\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .form-outline {\n");
      out.write("      position: relative;\n");
      out.write("      margin-bottom: 1.5rem;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .form-outline input {\n");
      out.write("      width: 100%;\n");
      out.write("      padding: 1rem;\n");
      out.write("      border: none;\n");
      out.write("      border-bottom: 2px solid #ffcc00; /* Bottom border color */\n");
      out.write("      border-radius: 0;\n");
      out.write("      background-color: transparent; /* Transparent background */\n");
      out.write("      color: black; /* Input text color */\n");
      out.write("      transition: border-color 0.3s;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .form-outline input:focus {\n");
      out.write("      outline: none;\n");
      out.write("      border-color: #ffcc00; /* Focus border color */\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .form-label {\n");
      out.write("      position: absolute;\n");
      out.write("      top: 0.5rem;\n");
      out.write("      left: 1rem;\n");
      out.write("      color: #999; /* Label color */\n");
      out.write("      transition: transform 0.3s, color 0.3s;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .form-outline input:placeholder-shown + .form-label {\n");
      out.write("      opacity: 0;\n");
      out.write("      transform: translateY(1rem);\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .btn-primary {\n");
      out.write("      background-color: #ffcc00; /* Button background color */\n");
      out.write("      border: none;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .btn-primary:hover {\n");
      out.write("      background-color: #e6b800; /* Hover state background color */\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .btn-primary:active {\n");
      out.write("      background-color: #b38f00; /* Active state background color */\n");
      out.write("    }\n");
      out.write("  </style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("<form class=\"vh-100\"   action=\"login\" method=\"POST\">\n");
      out.write("  <div class=\"container py-5 h-100\">\n");
      out.write("    <div class=\"row d-flex justify-content-center align-items-center h-100\">\n");
      out.write("      <div class=\"col-12 col-md-8 col-lg-6 col-xl-5\">\n");
      out.write("        <div class=\"card shadow-2-strong\">\n");
      out.write("          <div class=\"card-body p-5 text-center\">\n");
      out.write("\n");
      out.write("            <h3 class=\"fs-2 mb-5\"> Login </h3>\n");
      out.write("\n");
      out.write("            <div class=\"form-outline mb-4\">\n");
      out.write("              <input type=\"email\" id=\"typeEmailX-2\" class=\"form-control form-control-lg\" name=\"email\" required/>\n");
      out.write("              <label class=\"form-label\" for=\"typeEmailX-2\" style=\"margin-bottom: 20px;\">Email</label>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <div class=\"form-outline mb-4\">\n");
      out.write("              <input type=\"password\" id=\"typePasswordX-2\" class=\"form-control form-control-lg\" name=\"password\" required/>\n");
      out.write("              <label class=\"form-label\" for=\"typePasswordX-2\" style=\"margin-bottom: 10px;\">Password</label>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <p>Not a User? <a href=\"register.jsp\" class=\"text-warning\">Sign Up</a></p>\n");
      out.write("\n");
      out.write("            ");

              if(request.getAttribute("error")!=null){
               out.print("<p class='text-danger'>Invalid credentials!</p>");
              }
            
      out.write("\n");
      out.write("\n");
      out.write("            <input class=\"btn btn-primary btn-lg btn-block\" type=\"submit\"  value=\"Login\"/>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("</form>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
